services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=totolabricot
      - MYSQL_USER=user
      - MYSQL_PASSWORD=totolabricot
      - MYSQL_DATABASE=user

  server:
    image: log4shell:server
    volumes:
      - ./attacker/class:/app/shared

  build:
    image: log4shell:builder
    volumes:
      - ./attacker/java:/app/java
      - ./attacker/class:/app/class

  victim:
    image: log4shell:victim
    links:
      - server:server
      - mariadb:mariadb
    depends_on:
      - mariadb

  logger:
    image: log4shell:logger
    volumes:
      - ./attacker/logs:/app/logs
